### ISSUE TITLE
Signature verification

### ISSUE THREAD

**Issue by platonfloria** [dimitrykislichenko/xdefi-test#1]
Hello Dimitry.
As of now it is not clear from code if generated signature is valid.
Would it be possible for you to add signature verification?
You can do it either in UI or in wasm package tests.

**Comment by hinterlist** [comment]
@platonfloria sure, will update the code in couple hours.

**Comment by hinterlist** [comment]
@platonfloria I've added `verify` method to the the package and covered it with test.
